version: '3.4'

services:

  recipe:
    build:
      context: ./../Recipe_test
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 1
    links:
      - postgres



  postgres:
    image: 'postgres:14.7'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: recipe
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
      - ./init.init.sql:/docker-entrypoint-initdb.d/init.init.sql