version: '3'

services:

  recipe:
    build:
      context: ./../Recipe_test
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=12345 dbname=recipe sslmode=disable timezone=UTC connect_timeout=5 "




  postgres:
    image: 'postgres:14.4'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: recipe
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/