version: '3'

services:

  telegrambot:
    build:
      context: ./../../reciept
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8000:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres  dbname=recipe sslmode=disable timezone=UTC connect_timeout=5 password=12345"




  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: recipe
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/